services:
  envio-postgres:
    image: ghcr.io/hydradatabase/hydra:latest
    restart: always
    ports:
      - "${ENVIO_PG_PORT:-5433}:5432"
    volumes:
      - db_data_hydra:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${ENVIO_POSTGRES_PASSWORD:-testing}
      POSTGRES_USER: ${ENVIO_PG_USER:-postgres}
      POSTGRES_DB: ${ENVIO_PG_DATABASE:-envio-dev}
    networks:
      - my-proxy-net
  # metabase:
  #   image: metabase/metabase:v0.48.10
  #   ports:
  #   - "3000:3000"
  #   depends_on:
  #   - envio-postgres
  #   restart: always
  #   environment:
  #     MB_DB_TYPE: postgres
  #     MB_DB_USER: *metabase_user
  #     MB_DB_PASS: *metabase_password
  #     MB_DB_DBNAME: *metabase_db
  #     MB_DB_HOST: postgres
  #     MB_DB_POST: 5432
volumes:
  db_data_hydra:
  ganache-data:
networks:
  my-proxy-net:
    name: local_test_network
